version: '3.2'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 8000:8080
  catalog:
    build: ./catalog
    container_name: catalog
    restart: always
    ports:
      - 8001:8080
  order:
    build: ./order
    container_name: order
    restart: always
    ports:
      - 8002:8080
  sqlite:
    build: ./sqlite
    container_name: sqlite
    restart: always
    volumes:
      - ./sqlite:/db
    environment:
      - SQLITE_DB_NAME=bookstore.db
