version: '3.2'
services:
  catalog:
    build: ./catalog
    container_name: catalog
    restart: always
    environment:
      - SQLITE_DB_NAME=bookstore.db
      - DB_QUERY_LOG=catalog.log
    volumes:
      - ./sqlite:/db
      - ./logs:/logs
    network_mode: "host"
    depends_on:
      - sqlite
  sqlite:
    build: ./sqlite
    container_name: sqlite
    restart: always
    volumes:
      - ./sqlite:/db
    environment:
      - SQLITE_DB_NAME=bookstore.db
